-- Grants roles access to current and future objects. Run after 01_roles.sql as
-- SECURITYADMIN.

USE ROLE SECURITYADMIN;

-- OPENAQ_PIPELINE can access the warehouse, database, and medallion schemas.
GRANT USAGE ON WAREHOUSE OPENAQ_WH TO ROLE OPENAQ_PIPELINE;
GRANT USAGE ON DATABASE  OPENAQ    TO ROLE OPENAQ_PIPELINE;

GRANT USAGE ON SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT USAGE ON SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT USAGE ON SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL    TABLES IN SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL    TABLES IN SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL    TABLES IN SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;

GRANT SELECT ON ALL    VIEWS IN SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OPENAQ.BRONZE TO ROLE OPENAQ_PIPELINE;
GRANT SELECT ON ALL    VIEWS IN SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OPENAQ.SILVER TO ROLE OPENAQ_PIPELINE;
GRANT SELECT ON ALL    VIEWS IN SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OPENAQ.GOLD   TO ROLE OPENAQ_PIPELINE;

-- OPENAQ_CI has full access to the CI schema and no access to the main schemas.
GRANT USAGE ON WAREHOUSE OPENAQ_WH TO ROLE OPENAQ_CI;
GRANT USAGE ON DATABASE  OPENAQ    TO ROLE OPENAQ_CI;

GRANT ALL PRIVILEGES ON SCHEMA OPENAQ.CI TO ROLE OPENAQ_CI;
GRANT ALL PRIVILEGES ON ALL    TABLES IN SCHEMA OPENAQ.CI TO ROLE OPENAQ_CI;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA OPENAQ.CI TO ROLE OPENAQ_CI;
GRANT ALL PRIVILEGES ON ALL    VIEWS  IN SCHEMA OPENAQ.CI TO ROLE OPENAQ_CI;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA OPENAQ.CI TO ROLE OPENAQ_CI;

-- OPENAQ_READ has optional read-only access to GOLD.
GRANT USAGE ON WAREHOUSE OPENAQ_WH TO ROLE OPENAQ_READ;
GRANT USAGE ON DATABASE  OPENAQ    TO ROLE OPENAQ_READ;
GRANT USAGE ON SCHEMA    OPENAQ.GOLD TO ROLE OPENAQ_READ;

GRANT SELECT ON ALL    TABLES IN SCHEMA OPENAQ.GOLD TO ROLE OPENAQ_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENAQ.GOLD TO ROLE OPENAQ_READ;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA OPENAQ.GOLD TO ROLE OPENAQ_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA OPENAQ.GOLD TO ROLE OPENAQ_READ;
