-- Creates the bronze tables used by OpenAQ ingestion, auditing, and reconciliation.

USE ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS OPENAQ.BRONZE.MEASUREMENTS (
    SENSOR_ID NUMBER(38, 0) NOT NULL,
    PARAMETER_ID NUMBER(38, 0) NOT NULL,
    MEASUREMENT_PERIOD_FROM_UTC TIMESTAMP_TZ NOT NULL,
    RAW_MEASUREMENT VARIANT NOT NULL,
    LOAD_ID VARCHAR NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON COLUMN OPENAQ.BRONZE.MEASUREMENTS.MEASUREMENT_PERIOD_FROM_UTC IS
    'Part of the source measurement identity; separates adjacent hourly measurements.';

CREATE TABLE IF NOT EXISTS OPENAQ.BRONZE.SENSOR_AUDIT_RESULTS (
    AUDIT_ID VARCHAR NOT NULL,
    AUDITED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    AUDIT_FROM_UTC TIMESTAMP_TZ NOT NULL,
    AUDIT_TO_UTC TIMESTAMP_TZ NOT NULL,
    PROVIDER_ID NUMBER(38, 0),
    PROVIDER_NAME VARCHAR,
    LOCATION_ID NUMBER(38, 0) NOT NULL,
    LOCATION_NAME VARCHAR,
    SENSOR_ID NUMBER(38, 0) NOT NULL,
    SENSOR_NAME VARCHAR,
    PARAMETER_ID NUMBER(38, 0) NOT NULL,
    PARAMETER_NAME VARCHAR NOT NULL,
    AUDIT_RESULT VARCHAR NOT NULL,
    RECORD_COUNT NUMBER(38, 0) NOT NULL,
    OLDEST_MEASUREMENT_AT TIMESTAMP_TZ,
    NEWEST_MEASUREMENT_AT TIMESTAMP_TZ,
    ERROR_DETAIL VARCHAR
);

COMMENT ON COLUMN OPENAQ.BRONZE.SENSOR_AUDIT_RESULTS.AUDIT_FROM_UTC IS
    'Start of the period checked for this sensor.';
COMMENT ON COLUMN OPENAQ.BRONZE.SENSOR_AUDIT_RESULTS.AUDIT_TO_UTC IS
    'End of the period checked for this sensor.';
COMMENT ON COLUMN OPENAQ.BRONZE.SENSOR_AUDIT_RESULTS.OLDEST_MEASUREMENT_AT IS
    'Earliest returned measurement; shows where source data begins in the checked period.';
COMMENT ON COLUMN OPENAQ.BRONZE.SENSOR_AUDIT_RESULTS.NEWEST_MEASUREMENT_AT IS
    'Latest returned measurement; shows where source data ends in the checked period.';

CREATE TABLE IF NOT EXISTS OPENAQ.BRONZE.LOAD_SUMMARY (
    LOAD_ID VARCHAR NOT NULL,
    LOAD_TYPE VARCHAR NOT NULL,
    REFRESH_FROM_UTC TIMESTAMP_TZ NOT NULL,
    REFRESH_TO_UTC TIMESTAMP_TZ NOT NULL,
    API_RECORD_COUNT NUMBER(38, 0) NOT NULL,
    NEW_RECORD_COUNT NUMBER(38, 0) NOT NULL,
    CHANGED_RECORD_COUNT NUMBER(38, 0) NOT NULL,
    ABSENT_RECORD_COUNT NUMBER(38, 0) NOT NULL,
    OLDEST_NEW_MEASUREMENT_AT TIMESTAMP_TZ,
    BRONZE_CHANGED BOOLEAN NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON COLUMN OPENAQ.BRONZE.LOAD_SUMMARY.REFRESH_FROM_UTC IS
    'Start of the data range this summary describes.';
COMMENT ON COLUMN OPENAQ.BRONZE.LOAD_SUMMARY.REFRESH_TO_UTC IS
    'End of the data range this summary describes.';
COMMENT ON COLUMN OPENAQ.BRONZE.LOAD_SUMMARY.ABSENT_RECORD_COUNT IS
    'Measurements that had been in bronze but were no longer returned by the API.';
COMMENT ON COLUMN OPENAQ.BRONZE.LOAD_SUMMARY.OLDEST_NEW_MEASUREMENT_AT IS
    'Oldest timestamp among measurements newly seen in bronze; exposes late source backfill.';
