-- Deletes every resource created by the bootstrap, including all database data.
-- Use only to reset the Snowflake environment. Every statement is safe to re-run.

USE ROLE USERADMIN;
DROP USER IF EXISTS AIRFLOW_USER;
DROP USER IF EXISTS OPENAQ_CI_USER;
DROP ROLE IF EXISTS OPENAQ_PIPELINE;
DROP ROLE IF EXISTS OPENAQ_CI;
DROP ROLE IF EXISTS OPENAQ_READ;

USE ROLE SYSADMIN;
DROP DATABASE  IF EXISTS OPENAQ;
DROP WAREHOUSE IF EXISTS OPENAQ_WH;
