select
    sensor_id,
    parameter_id,
    measurement_period_from_utc,
    try_to_double(raw_measurement:value::varchar) as measurement_value,
    raw_measurement:parameter:name::varchar as parameter_name,
    raw_measurement:parameter:units::varchar as parameter_unit,
    raw_measurement:parameter:displayName::varchar as parameter_display_name,
    raw_measurement:period:label::varchar as period_label,
    raw_measurement:period:interval::varchar as period_interval,
    try_to_timestamp_tz(raw_measurement:period:datetimeFrom:utc::varchar) as period_started_at_utc,
    try_to_timestamp_tz(raw_measurement:period:datetimeFrom:local::varchar) as period_started_at_local,
    try_to_timestamp_tz(raw_measurement:period:datetimeTo:utc::varchar) as period_ended_at_utc,
    try_to_timestamp_tz(raw_measurement:period:datetimeTo:local::varchar) as period_ended_at_local,
    try_to_timestamp_tz(raw_measurement:coverage:datetimeFrom:utc::varchar) as coverage_started_at_utc,
    try_to_timestamp_tz(raw_measurement:coverage:datetimeFrom:local::varchar) as coverage_started_at_local,
    try_to_timestamp_tz(raw_measurement:coverage:datetimeTo:utc::varchar) as coverage_ended_at_utc,
    try_to_timestamp_tz(raw_measurement:coverage:datetimeTo:local::varchar) as coverage_ended_at_local,
    raw_measurement:coverage:expectedInterval::varchar as coverage_expected_interval,
    raw_measurement:coverage:observedInterval::varchar as coverage_observed_interval,
    try_to_number(raw_measurement:coverage:expectedCount::varchar, 38, 0) as coverage_expected_count,
    try_to_number(raw_measurement:coverage:observedCount::varchar, 38, 0) as coverage_observed_count,
    try_to_double(raw_measurement:coverage:percentComplete::varchar) as coverage_percent_complete,
    try_to_double(raw_measurement:coverage:percentCoverage::varchar) as coverage_percent_coverage,
    try_to_boolean(raw_measurement:flagInfo:hasFlags::varchar) as has_flags,
    raw_measurement:coordinates as measurement_coordinates,
    raw_measurement:summary as measurement_summary,
    load_id,
    loaded_at,
    raw_measurement
from {{ source('bronze', 'measurements') }}
