select
    load_id,
    snapshot_at,
    raw_location:id::number(38, 0) as location_id,
    raw_location:name::varchar as location_name,
    raw_location:locality::varchar as locality,
    raw_location:country:id::number(38, 0) as country_id,
    raw_location:country:code::varchar as country_code,
    raw_location:country:name::varchar as country_name,
    raw_location:provider:id::number(38, 0) as provider_id,
    raw_location:provider:name::varchar as provider_name,
    raw_location:owner:id::number(38, 0) as owner_id,
    raw_location:owner:name::varchar as owner_name,
    try_to_double(raw_location:coordinates:latitude::varchar) as latitude,
    try_to_double(raw_location:coordinates:longitude::varchar) as longitude,
    try_to_timestamp_tz(raw_location:datetimeFirst:utc::varchar) as first_measurement_at_utc,
    try_to_timestamp_tz(raw_location:datetimeFirst:local::varchar) as first_measurement_at_local,
    try_to_timestamp_tz(raw_location:datetimeLast:utc::varchar) as last_measurement_at_utc,
    try_to_timestamp_tz(raw_location:datetimeLast:local::varchar) as last_measurement_at_local,
    raw_location:timezone::varchar as timezone,
    try_to_boolean(raw_location:isMobile::varchar) as is_mobile,
    try_to_boolean(raw_location:isMonitor::varchar) as is_monitor,
    raw_location:bounds as bounds,
    raw_location:distance as distance,
    raw_location:instruments as instruments,
    raw_location:licenses as licenses,
    raw_location:sensors as sensors,
    loaded_at,
    raw_location
from {{ source('bronze', 'location_snapshots') }}
